@ProductManagement.API_HostAddress = http://localhost:5166

GET {{ProductManagement.API_HostAddress}}/weatherforecast/
Accept: application/json

GET {{ProductManagement.API_HostAddress}}/api/product
Accept: application/json
###
